# Generated by Django 6.0.3 on 2026-04-30 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('cleanup', 'Clean-up Drive'), ('feeding', 'Feeding Program'), ('medical', 'Medical Mission'), ('sports', 'Sports Tournament'), ('assembly', 'Barangay Assembly'), ('seminar', 'Disaster Preparedness Seminar'), ('other', 'Other Community Event')], max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventCoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Barangay Organizer'), ('volunteer', 'Volunteer'), ('resident', 'Resident / Participant')], default='resident', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('registered', 'Registered'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='events.eventcoreuser')),
            ],
            options={
                'db_table': 'participants',
                'ordering': ['event', 'user'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Needs Improvement'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='events.event')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='events.participant')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('supplies', 'Supplies'), ('food', 'Food'), ('medicine', 'Medicine'), ('venue', 'Venue'), ('other', 'Other')], default='supplies', max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('available', 'Available'), ('used', 'Used'), ('returned', 'Returned'), ('damaged', 'Damaged')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='events.event')),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['event', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(blank=True, max_length=150)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_assignments', to='events.event')),
                ('organizer', models.ForeignKey(limit_choices_to={'role': 'organizer'}, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='events.eventcoreuser')),
            ],
            options={
                'verbose_name': 'Event Organizer',
                'verbose_name_plural': 'Event Organizers',
                'db_table': 'event_organizers',
                'ordering': ['event', 'organizer'],
                'unique_together': {('event', 'organizer')},
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_assigned', models.CharField(blank=True, max_length=150)),
                ('attendance_status', models.CharField(choices=[('registered', 'Registered'), ('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='events.event')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'volunteer'}, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to='events.eventcoreuser')),
            ],
            options={
                'db_table': 'volunteers',
                'ordering': ['event', 'user'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
